### ISSUE TITLE
Allow using the master view without a preselected detail

### ISSUE THREAD

**Issue by bilak** [appreciated/master-detail-view#1]
Hello, 
is it somehow possible to invoke master-detail view without using parameter in url? For example if I have url `localhost:8080/master/detail` can I invoke it without using something like `localhost:8080/master/detail/1`?

**Comment by appreciated** [comment]
I guess I will need more detail about what you are trying to archive. 
This addon was made to create uis with the following behavior
![https://i.stack.imgur.com/DKBMq.png](https://i.stack.imgur.com/DKBMq.png).

So on the left hand you have a selectable List with items. on the right hand there is (always) the detail of a selected element visible. 
Whatsoever on mobile devices there is not enough space to do this, so instead of shrinking the content the detail will only be shown when an element is selected. 

How does you usecase differs from the description above?

**Comment by bilak** [comment]
Let's say I use app layout with menus like orders, users, ... For data loading (activity A on images you posted) I'm using grid with lazy-loading. So at the moment when I click on orders menu I don't know about orders presented in that view. But If I navigate to `localhost:8080/orders` (which should be the master view) Vaadin tels me that it needs parameter ..for example `localhost:8080/orders/-1` is valid too. Is there way how to load `localhost:8080/orders` without providing parameter `-1` and just load the main view with data being lazy-loaded?

**Comment by appreciated** [comment]
This view currently requires (when using the expanded mode) to preselect an order.
